export const global = {
    getters: {
        CURRENT_COMPANY: 'CURRENT_COMPANY',
        LOCALE: 'LOCALE'
    },
    actions: {
        LOGIN: 'LOGIN',
        LOGOUT: 'LOGOUT',
        GET_OR_RECOVER_LOGIN_INFO: 'GET_OR_RECOVER_LOGIN_INFO',
        GET_COMPANIES: 'GET_COMPANIES',
        SET_LANGUAGE: 'SET_LANGUAGE',
        SET_TIMEZONE: 'SET_TIMEZONE'
    },
    mutations: {
        SET_THEME: 'SET_THEME',
        SET_LOGIN_INFO: 'SET_LOGIN_INFO',
        SET_COMPANIES: 'SET_COMPANIES',
        SET_CURRENT_COMPANY: 'SET_CURRENT_COMPANY',
        CHANGE_COMPANY_SELECTOR_STATE: 'CHANGE_COMPANY_SELECTOR_STATE',
        HAS_LOGGED_ON: 'HAS_LOGGED_ON',
        CHANGE_PASSWORD_STATE: 'CHANGE_PASSWORD_STATE',
        SET_ASIDE_ACTIVE_INDEX: 'SET_ASIDE_ACTIVE_INDEX',
        SET_HEADER_ACTIVE_INDEX: 'SET_HEADER_ACTIVE_INDEX',
        SET_PAGE_REFER: 'SET_PAGE_REFER',
        SET_CLIENT_WIDTH: 'SET_CLIENT_WIDTH',
        SET_LANGUAGE: 'SET_LANGUAGE',
        SET_TIMEZONE: 'SET_TIMEZONE',
        SET_LOCALE_SELECTOR_STATE: "SET_LOCALE_SELECTOR_STATE",
        SET_MODULES: "SET_MODULES"
    }
}
