 export default {
   login:  "/login",
   DataService: "/",
   VehicleList: "vehicles",
   trips: "vehicles/:vehicle_id/trips",
   position: "devices/:deviceId/position",
   vehiclesTrips: "trips/:trip_id",
   merge: "trips/merge/:vehicle_id",
   EventList: "events/type/normal",
   EmergencyList: "events/type/emergency",
   eventDetails: "events/:event_id",
   StatisticsBasic: "statistics/basic",
   StatisticsDevice: "statistics/device",
   Console: "/console",
   DeviceList: "/console/devices",
   FenceList: "/console/fences",
   LogList:"/console/logs",
   VehicleList: "/console/vehicles",
   User: "/console/users",
   Company: "/console/companies",
   RoleList: "/console/roles",
}